// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okbvkhwmsfccxnlrkouc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rYnZraHdtc2ZjY3hubHJrb3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTg3NTAsImV4cCI6MjA2MzE5NDc1MH0.1taRzrJ8Wg7lB37FhO1L6rx65ZxvTJakXyZdbfKWlhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);